# Generated by Django 4.2.13 on 2024-07-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(unique=True)),
                ('isbn', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('soon', models.BooleanField(default=False)),
                ('new', models.BooleanField(default=False)),
                ('genre', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('series', models.CharField(blank=True, max_length=100, null=True)),
                ('cycle_book', models.CharField(blank=True, max_length=100, null=True)),
                ('publisher', models.CharField(max_length=30)),
                ('the_year_of_publishing', models.IntegerField()),
                ('number_of_pages', models.IntegerField()),
                ('age_restriction', models.IntegerField()),
                ('cover_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('rating_value', models.FloatField(default=0)),
                ('rating_count', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_link', models.URLField()),
                ('url', models.URLField()),
                ('special_edition', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.IntegerField(default=0, unique=True)),
                ('isbn', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('pros', models.TextField()),
                ('cons', models.TextField()),
                ('rating', models.FloatField()),
                ('review_date', models.DateTimeField()),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=0, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('favorite_genres', models.CharField(max_length=255)),
                ('favorite_tags', models.CharField(max_length=255)),
                ('disliked_tags', models.CharField(max_length=255)),
                ('author_subscriptions', models.CharField(max_length=255)),
                ('search_queries', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=60)),
                ('date', models.DateTimeField()),
                ('reaction_type', models.CharField(max_length=20)),
                ('duration_viewed', models.IntegerField()),
                ('evaluation', models.IntegerField()),
            ],
        ),
    ]
